version: 1.0.{build}
configuration: 
#- Debug
- Release
platform: Win32
clone_folder: C:\Projects\Github\imgui
build:
  project: ./examples/imgui_examples.sln
  verbosity: minimal

after_build:
#  -ps: 
ps: |
7z a $env:APPVEYOR_BUILD_FOLDER\$env:APPVEYOR_BUILD_VERSION.zip $env:APPVEYOR_BUILD_FOLDER\examples\example_win32_directx9\Release\example_win32_directx9.exe $env:APPVEYOR_BUILD_FOLDER\examples\example_win32_directx10\Release\example_win32_directx10.exe $env:APPVEYOR_BUILD_FOLDER\examples\example_win32_directx11\Release\example_win32_directx11.exe $env:APPVEYOR_BUILD_FOLDER\examples\example_glfw_opengl2\Release\example_glfw_opengl2.exe $env:APPVEYOR_BUILD_FOLDER\examples\example_glfw_opengl3\Release\example_glfw_opengl3.exe
Push-AppveyorArtifact $env:APPVEYOR_BUILD_VERSION.zip

#artifacts:
#- path: .\examples\example_win32_directx9\Release\example_win32_directx9.exe
#  name: example_win32_directx9.exe
#- path: .\examples\example_win32_directx10\Release\example_win32_directx10.exe
#  name: example_win32_directx10.exe
#- path: .\examples\example_win32_directx11\Release\example_win32_directx11.exe
#  name: example_win32_directx11.exe
#- path: .\examples\example_glfw_opengl2\Release\example_glfw_opengl2.exe
#  name: example_glfw_opengl2.exe
#- path: .\examples\example_glfw_opengl3\Release\example_glfw_opengl3.exe
#  name: example_glfw_opengl3.exe
#- path: .\$env:APPVEYOR_BUILD_VERSION.zip
#  name: $env:APPVEYOR_BUILD_VERSION.zip

deploy:
- provider: GitHub
  auth_token:
    secure: jh3HUO1hV25i75MT9+1c4mBG2wE3X+RWfF+X/Qe6aqedRwHrTVN690kFmu4glHsu
  artifact: $env:APPVEYOR_BUILD_VERSION.zip
  #draft: true
    #prerelease: true
    #on:
      #branch: master                # release from master branch only
      #configuration: Release
      #APPVEYOR_REPO_TAG: true       # deploy on tag push only
  #draft: true
  prerelease: true
  force_update: true
