version: 1.0.{build}
configuration: Release
platform: Win32
clone_folder: C:\Projects\Github\imgui
build:
  project: ./examples/imgui_examples.sln
  verbosity: minimal
artifacts:
- path: C:\Projects\Github\imgui\examples\example_win32_directx9\Release\example_win32_directx9.exe
  name: example_win32_directx9.exe